### ISSUE TITLE
Questions about cppcon 2016 presentation

### ISSUE THREAD

**Issue by cyberkm** [lefticus/presentations#2]
Hi Jason, I am watching your "Practical Performance Practices" presentation, and as i want it some questions arise, I'll be adding them as issues while a progress through presentation. I hope you'll be kind to answer them.
1. The int structure.

```
struct Int
{
  Int(const std::string &t_s) : m_i(std::atoi(t_s.c_str()))
  { }

  int val() const {
    return m_i;
  }

  int m_i;
};
```

If we ignore all those struct and brackets code, what we have is just a wrapper around std::atoi()
what is executed only once, and stores the data in one single const integer. (in this case its not even private but i guess it was just to save slide space).

So the question is: Why would one want to write this struct with all this code while
in fact single line would be sufficient.

`const int blah = std::atoi(mystring.c_str()));`

**Comment by lefticus** [comment]
The point was to extract real world use cases from ChaiScript. In this case, the 'int' is wrapped in some generic code, and as I said in the talk, it took quite some time to realize I was recalculating it on each call because it was buried in a virtual function call.

This is a link to the real code that was fixed to only calculate once, and basically has to stay wrapped in a class.

https://github.com/ChaiScript/ChaiScript/blob/bbe89e61bcad0a6b7f3dbde0780964919e0292e9/include/chaiscript/language/chaiscript_eval.hpp#L89-L98
